from . import authent_routes
from . import banned_users_routes
from . import comment_routes
from . import event_routes
from . import like_routes
from . import payment_routes
from . import profile_routes
from . import reason_routes
from . import registration_routes
from . import signaled_comment_routes
from . import signaled_event_routes
from . import signaled_user_routes
from . import super_admin_routes
from . import type_routes
from . import user_routes
